springdoc:
  swagger-ui:
    path: /api
spring:
  application:
    name: sodd
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
    allow-circular-references: true
  profiles:
    active: local
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  datasource:
    mysql:
      jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        properties:
          hibernate:
            dialect: ${mysql.jpa.database-platform}
            hbm2ddl:
              auto: ${mysql.jpa.hibernate.ddl-auto}
            show_sql: ${mysql.jpa.show-sql}
            format_sql: ${mysql.jpa.show-sql}
      datasource:
        driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url: ${sodd.database.mysql.url}
        username: ${sodd.database.mysql.account}
        password: ${sodd.database.mysql.password}
    mssql:
      jpa:
        database-platform: org.hibernate.dialect.SQLServerDialect
        properties:
          hibernate:
            dialect: ${mssql.jpa.database-platform}
            hbm2ddl:
              auto: ${mssql.jpa.hibernate.ddl-auto}
            show_sql: ${mssql.jpa.show-sql}
            format_sql: ${mssql.jpa.show-sql}
      datasource:
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        url: ${sodd.database.mssql.url}
        username: ${sodd.database.mssql.account}
        password: ${sodd.database.mssql.password}
  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: ${spring.jpa.show-sql}
  primary-datasource: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${sodd.mail.account}
    password: ${sodd.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  image:
    url: '${server.path}${server.servlet.context-path}${server.image.name}'
  file:
    url: '${server.path}${server.servlet.context-path}${server.file.name}'
logging:
  config: classpath:log4j2.yml
  level:
    jdbc:
      sqlonly: off
      audit: off
      resultset: off
      connection: off
