server:
  path: http://IP:{port}
  image:
    name: image
    path: '存放路徑 Ex: D:\sodd\UploadFile\${server.image.name}\'
  file:
    name: file
    path: '存放路徑 Ex: D:\sodd\UploadFile\${server.file.name}\'
logging:
  level:
    sqltiming: DEBUG
    resultsettable: DEBUG
security:
  jwt:
    secret:
google:
  clientId:
  clientSecret:
llama3:
  path: "llama server路徑 Ex:http://localhost:1234/v1"
  model: "使用的模型 Ex: QuantFactory/Meta-Llama-3-8B-Instruct-GGUF"
sodd:
  database:
    mysql:
      url: jdbc:log4jdbc:mysql://{資料庫IP}:{port}/{資料庫名字}?serverTimezone=Asia/Taipei
      account: 帳號
      password: 密碼
    mssql:
      url: jdbc:sqlserver://{資料庫IP}:{port(如果MSSQL有設定的話)};databaseName={資料庫名子}
      account: 帳號
      password: 密碼
  mail:
    account: "寄信帳號"
    password: "帳號應用程式密碼"
